### ISSUE TITLE
[이민희] 알고리즘 기초 1/2 checklist

### ISSUE THREAD

**Issue by MoOo2mm** [MoOo2mm/SSUalgo#17]
#### 200 - 자료구조 1
- [x] 스택 
- [x] 단어 뒤집기 
- [x] 괄호
- [x] 스택 수열
- [x] 에디터
- [x] 큐
- [x] 조세퍼스 문제
- [x] 덱
#### 201 - 자료구조 1 (연습)
- [x] 단어 뒤집기 2
- [x] 쇠막대기
- [x] 오큰수
- [x] 오등큰수
#### 203 - 자료구조 1 (참고)
- [x] 후위 표기식2
- [x] 후위 표기식
- [x] 알파벳 개수
- [x] 알파벳 찾기
- [x] 문자열 분석
- [x] 단어 길이 재기
- [x] ROT13
- [x] 네 수
- [x] 접미사 배열
#### 300 - 수학 1
- [x] 나머지
- [x] 최대공약수와 최소공배수
- [x] 최소공배수
- [x] 소수 찾기
- [x] 소수 구하기
- [x] 골드바흐의 추측
- [x] 팩토리얼
- [x] 팩토리얼 0의 개수
- [x] 조합 0의 개수
#### 301 - 수학 1 (연습)
- [x] GCD 합
- [x] 숨바꼭질 6
- [x] 2진수 8진수
- [x] 8진수 2진수
- [x] 2진수
- [x] 골드바흐 파티션
#### 303 - 수학 1 (참고)
- [x] 진법 변환 2
- [x] 진법 변환
- [x] Base Conversion
- [x] 소인수분해
#### 400 - 다이나믹 프로그래밍 1
- [x] 1로 만들기
- [x] 2×n 타일링
- [x] 2×n 타일링 2
- [x] 1, 2, 3 더하기
- [x] 카드 구매하기
- [x] 카드 구매하기 2
- [x] 1, 2, 3 더하기 5
- [x] 쉬운 계단 수
- [x] 이친수
- [x] 가장 긴 증가하는 부분 수열
- [x] 가장 긴 증가하는 부분 수열 4
- [x] 연속합
- [x] 제곱수의 합
- [x] 합분해
#### 401 - 다이나믹 프로그래밍 1 (연습)
- [x] 1, 2, 3 더하기 3
- [x] RGB거리
- [x] 동물원
- [x] 오르막 수
- [x] 스티커
- [x] 포도주 시식
- [x] 정수 삼각형
- [x] 가장 큰 증가 부분 수열
- [x] 가장 긴 감소하는 부분 수열
- [x] 가장 긴 바이토닉 부분 수열
- [x] 연속합 2
- [x] 타일 채우기
#### 402 - 다이나믹 프로그래밍 1 (도전)
- [x] 동물원
- [x] RGB거리 2
- [x] 합분해
