### ISSUE TITLE
[이민희] 알고리즘 중급 1/3 checklist

### ISSUE THREAD

**Issue by MoOo2mm** [MoOo2mm/SSUalgo#26]
### 521 - 브루트 포스 - 순열 (연습)
- [ ] 부등호
- [ ] 단어 수학
- [ ] 연산자 끼워넣기
- [ ] 스타트와 링크
### 531 - 브루트 포스 - 재귀 (연습)
- [ ] 로또
- [ ] 부분수열의 합
- [ ] 부분수열의 합
- [ ] 연산자 끼워넣기
- [ ] 연산자 끼워넣기 (2)
- [ ] 테트로미노
- [ ] 두 동전
- [ ] 에너지 모으기
- [ ] N-Queen
- [ ] 스도쿠
- [ ] 스도미노쿠
- [ ] 알파벳
### 533 - 브루트 포스 - 재귀 (참고)
- [ ] 퇴사
### 541 - 브루트 포스 - 비트마스크 (연습)
- [ ] 부분수열의 합
- [ ] 가르침
- [ ] 구슬 탈출 2
- [ ] 2048 (Easy)
### 611 - BFS (연습)
- [ ] 뱀과 사다리 게임
- [ ] 데스 나이트
- [ ] DSLR
- [ ] 연구소
- [ ] 돌 그룹
- [ ] 벽 부수고 이동하기
- [ ] 벽 부수고 이동하기 4
- [ ] 벽 부수고 이동하기 2
- [ ] 벽 부수고 이동하기 3
- [ ] 움직이는 미로 탈출
- [ ] 탈출
- [ ] 아기 상어
- [ ] 레이저 통신
- [ ] 소수 경로
- [ ] 적록색약
- [ ] 4연산
### 710 - 그리디 알고리즘
- [ ] 동전 0
- [ ] 회의실배정
- [ ] ATM
- [ ] 행렬
- [ ] 전구와 스위치
- [ ] 동전 뒤집기
- [ ] 보석 도둑
- [ ] 순회강연
- [ ] 가장 긴 증가하는 부분 수열 2
### 711 - 그리디 알고리즘 (연습)
- [ ] 잃어버린 괄호
- [ ] 수 묶기
- [ ] 대회 or 인턴
- [ ] 30
- [ ] 병든 나이트
- [ ] AB
- [ ] A와 B
### 712 - 그리디 알고리즘 (도전)
- [ ] NMK
- [ ] 롤러코스터
- [ ] A와 B 2
### 800 - 분할 정복
- [ ] 숫자 카드
- [ ] 숫자 카드 2
- [ ] 배열 합치기
### 801 - 분할 정복 (연습)
- [ ] 종이의 개수
- [ ] 하노이 탑 이동 순서
- [ ] 트리의 순회
- [ ] Z
- [ ] 사분면
- [ ] 별 찍기 - 10
- [ ] 별 찍기 - 11
- [ ] 버블 소트
### 802 - 분할 정복 (도전)
- [ ] 스카이라인
- [ ] 가장 가까운 두 점
### 810 - 정렬
- [ ] 수 정렬하기 2
- [ ] 좌표 정렬하기
- [ ] 좌표 정렬하기 2
- [ ] 나이순 정렬
- [ ] 국영수
- [ ] 수 정렬하기 3
- [ ] 카드
- [ ] 버블 소트
### 820 - 이분 탐색
- [ ] 수 이어 쓰기 2
- [ ] 랜선 자르기
- [ ] 나무 자르기
- [ ] 공유기 설치
- [ ] 중량제한
- [ ] 사다리
- [ ] 선분과 점
### 821 - 이분 탐색 (연습)
- [ ] 기타 레슨
- [ ] 구간 나누기 2
- [ ] 배열에서 이동
- [ ] K번째 수
- [ ] 놀이 공원
